4 tasks
Galina1405/PY-111 pull request #4
Opened 2021-01-28 17:18 UTC by Galina1405

Сделано 4 задание

2021-01-28 18:01 UTC, aeksei requested changes

2021-01-28 18:01 UTC, aeksei commented on offset_py111/offest_4.py
> +        for j in range(1, len(coast)):
а если матрица не квадратная?

2021-01-29 20:17 UTC, Galina1405 commented on offset_py111/offest_4.py
> +        for j in range(1, len(coast)):
посмотрите, пожалуйста, я учла, что матрица может быть прямоугольной

2021-02-09 16:14 UTC, aeksei approved these changes
Проверено

---

Если стоит **Changes approved**, то смело можно сливать ветки. 
И после слияния удалять ветку.

Всё что указано просто комментариями, носит рекомендательный характер.
Для моментов, которые нужно исправить, я буду запрашивать изменения.

2021-02-17 20:27 UTC, merged